pipeline:
  input:
    http:
      type: rest_api
      account: '%akeneo_read_connection%'
      endpoint: '%endpoint%'
      method: GET
      multiple: true
      identifier_filter_list: '%attribute_options%'
  output:
    writer:
      type: jsonl
      filename: 'read/akeneo_%endpoint%.jsonl'
      skip_if_exists: true