sources:
  - '%workpath%/akeneo_%endpoint%.jsonl'

pipeline:
  input:
    reader:
      type: jsonl
      filename: 'akeneo_%endpoint%.jsonl'
  output:
    http:
      type: rest_api
      account: '%akeneo_write_connection%'
      endpoint: '%endpoint%'
      method: MULTI_PATCH
