name: PHP Composer

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false
      matrix:
        php-versions: ['8.4', '8.3', '8.2', '8.1', '8.0']

    steps:
    - uses: actions/checkout@v2

    - name: Whitelist IP
      uses: fjogeleit/http-request-action@master
      with:
        url: 'https://app-satis.induxx.be/1da6b409a6d4bfcb15a9/index.php'
        method: 'GET'

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest --ignore-platform-reqs

    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    - name: Run test suite
      run: composer github-test
